### ISSUE TITLE
rename from Gittip to Gratipay

### ISSUE THREAD

**Issue by chadwhitacre** [TigerND/gratipay-twisted#1]
Per https://medium.com/gratipay-blog/gratitude-gratipay-ef24ad5e41f9. :-)

**Comment by TigerND** [comment]
Renamed

**Comment by chadwhitacre** [comment]
Thanks! Gratipay README updated in https://github.com/gratipay/gratipay.com/commit/ea12554b9f16ac179a6c8d6f60a9f0dbd7c46184.
